### PR TITLE
Fixes wrong value for microsecs in a day

### LINKED ISSUE #1850: Conversion from `TimeTzADT` to `TimeWithTimeZone` is broken
It is due to wrong value at https://github.com/pgcentralfoundation/pgrx/blob/b4c444111814a51abb15a14669b95a080c51aed5/pgrx/src/datum/time_with_timezone.rs#L27.

It misses 3 additional zeros.

### PR DESCRIPTION
**Pull request by aykut-bozkurt**
`MICROSECONDS_PER_DAY` constant at `time_with_timezone.rs` misses 3 additional zeros for microseconds part.

That breaks conversion from `(pg_sys::TimeADT, i32)` to `TimeWithTimeZone`. 

Fixes #1850

### CODE REVIEW

File: pgrx/src/datum/time_with_timezone.rs [hunk 1]
```diff
@@ -24,7 +24,10 @@ use std::panic::{RefUnwindSafe, UnwindSafe};
 #[derive(Debug, Copy, Clone)]
 #[repr(transparent)]
 pub struct TimeWithTimeZone(pg_sys::TimeTzADT);
-const MICROSECONDS_PER_DAY: pg_sys::TimeADT = 86_400_000;
+
+// 86_400_000_000
```
Comment (YohDeadfall) [inline pgrx/src/datum/time_with_timezone.rs]: Thanks for the fix! Could you mention that it comes from the `USECS_PER_DAY` constant?

**Comment by eeeebbbbrrrr** [comment]
Thanks @aykut-bozkurt. Could you add a test for this in the pgrx-tests crate?  I believe there’s a module for date/time tests already.

File: pgrx/src/datum/time_with_timezone.rs (hunk 1 above)
Comment (aykut-bozkurt) [reply pgrx/src/datum/time_with_timezone.rs]: Makes sense, let's reuse that const across datetime module.

File: pgrx/src/datum/datetime_support/mod.rs [hunk 2]
```diff
@@ -24,6 +24,9 @@ mod ops;
 
 pub use ctor::*;
 
+pub const USECS_PER_SEC: i64 = 1_000_000;
+pub const USECS_PER_DAY: i64 = pg_sys::SECS_PER_DAY as i64 * USECS_PER_SEC;
```
Comment (YohDeadfall) [inline pgrx/src/datum/datetime_support/mod.rs:28]: @eeeebbbbrrrr, why does `pg_sys` has `SECS_PER_DAY` generated but not `USECS_PER_SEC`?

Comment (eeeebbbbrrrr) [reply pgrx/src/datum/datetime_support/mod.rs:28]: hmm.  Probably b/c of how it's defined in `timestamp.h`:

```c
#define USECS_PER_SEC	INT64CONST(1000000)
```

Kinda doubt bindgen can see through even that simple of a #define.

**Comment by workingjubilee** [comment]
I was very tired that week.
